#!/bin/bash

# Define command-line arguments

CMD=$1
RESOURCE_TYPE=$2
RESOURCE_NAME=$3
NAMESPACE=$4

# Check if the resource name is provided
if [[ -z $RESOURCE_NAME ]]; then
  echo "Please provide the resource name."
  exit 1
fi

# Check if the cmd is provided
if [ $CMD == "top" ]
then
  # Retrieve resource usage statistics from Kubernetes
  kubectl $CMD $RESOURCE_TYPE $RESOURCE_NAME -n $NAMESPACE | tail -n +2 | while read line;
  do
    # Extract CPU and memory usage from the output
    RESOURCE=$(echo $RESOURCE_TYPE)
    NAMESPACE=$(echo $NAMESPACE)
    NAME=$(echo $line | awk '{print $1}')
    CPU=$(echo $line | awk '{print $2}')
    MEMORY=$(echo $line | awk '{print $3}')

    echo "$RESOURCE, $NAMESPACE, $NAME, $CPU, $MEMORY"
  done;
elif [ $CMD == "logs" ]
  then
    kubectl $CMD -f $RESOURCE_NAME -n $NAMESPACE
else
  echo "Please provide the correct command, available commands are: top | logs"
  echo "You provided: $CMD"
  exit 1
fi
